# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: ASC (All Saints Code)
# Description of the Site
description: Blog for the ASC repo
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /WhatATheme/assets/images/Home.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: null@gmail.com
facebook_username: toussaintcruise
twitter_username: null
instagram_username: tuwookie
linkedin_username: null
github_username:  archisen
youtube_channel_id: null
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Tuwoo

# Name of the Author
author-name: Tuwookie
# URL for the Image of the Author
author-image: /WhatATheme/assets/images/Author.JPEG
# 60 Words About the Author
author-about: A place to Showcase my personal projects. I still have tofigure out a permenent name for the blog. ASC Stands for all saints cod e since my name means All saint's but I don't think I want to keep that name. 
So I guess stay tuned for any changes!
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Archisen

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
